### ISSUE TITLE
Landing Page While We Build

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#10]
_Note: this is the contents of a number of comments from another repo.  User's names have been place above the comments to keep a history of what was said._

---

**@melodykramer**

Things that need to be on the landing page before we launch the full site.
1. Explanation of project.
2. Ways to get involved depending on skillset and time you have
3. Blog updates (We have the ability to be entirely open along the way, and I'll take the lead on this.)
4. ???

What am I missing @GabeIsman @thequbit @nkkl @ismcodes

**Comment by GabeIsman** [comment]
I think our newsletter has largely eliminated the need for this at this point. http://mediapublic.github.io/ is perhaps a little sparse, but I think we should be focusing our efforts on getting the main site up and running.

**Comment by thequbit** [comment]
I agree.  I think the landing page is just fine for the time being.  Maybe some screen shots as we get closer to a deliverable.
