### ISSUE TITLE
Add Help Requests functionality

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#100]
@melodykramer writes:

> I just took a look and my one concern is not having the "items that people can help with" - would there be a way to have 
> 
> HelpItem1
> HelpItem2
> HelpItem3

So we could add a new table in the database that is "HelpRequests".  Those could then be listed on the `organization` page like `Podcasts` and `People`.  This could include:
- Organization
  - This would be linked to the organization in the `organizations` table
- Title
- Description
- Primary contact
  - This would be linked to a user in the user table, giving us name and contact info
- Due date
- Tags
  - Would be just a string of comma separated values.
  - Would include things like "graphic design", "coding", "community outreach", etc.

I think implementing that is pretty quick ( lot of code reuse I would suspect from Podcasts and People ).  Adding in more useful features such as clicking on a tag to see others like it might be outside of our MVP.

Thoughts?

**Comment by melodykramer** [comment]
That looks like a great MVP to me.

**Comment by GabeIsman** [comment]
I got this ticket confused with #101 earlier. We've decided on this and mostly implemented it, so I'm closing this question.
