### ISSUE TITLE
Design tiles for Podcasts/Recordings, People, and Help Requests

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#105]
#81 describes what information will be on the `Organization` page.  This page will have lists of Podcasts/Recordings, People, and Help Requests.  These will be in small "tiles" with information about each item.  These tiles need to be designed, so they can be reused on this page and other pages.

**Comment by nkkl** [comment]
+1 project management for @thequbit :)

**Comment by nkkl** [comment]
Focus on typographic hero images instead of loading up pictures.

**Comment by melodykramer** [comment]
Happy to look at mockups

**Comment by nkkl** [comment]
Addressed in https://github.com/mediapublic/mediapublic/pull/146

Please file feedback/change requests as new issues.
