### ISSUE TITLE
Figure out flow for editing sub-resources on org page (recordings, people, etc.)

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#111]
This is probably a general problem but I'm running into specifically while implementing the list of people on an organization: in-place editing doesn't work so well when the place is tiny. Some possible solutions:
- Every resource must have a dedicated single resource page (e.g. the person page, which we had thought to push off until after MVP), at least for editing
- We expand the space to just be however big it needs to be for the form.
- Some kind of modal popup maybe? 

Thoughts?

**Comment by thequbit** [comment]
First, I think modal is good (especially makes things easier for formatting on mobile). 

Second, why do we need to edit anything in a list or tile? I would expect that to all be read only stuff.  It's all bring pulled from other places (howtos, people (users), podcasts/recordings (comes from bookmarklet). Or am I missing something?

**Comment by nkkl** [comment]
Yeah, I think the lists/tiles are all being pulled from elsewhere. If we need to, we can have an edit entry point on those that would take you to the specific resource's edit page - or call up a modal. Editing them in-place isn't necessary; that's going to be most valuable for changing details about an organization on its page (ex. tweaking the description).

**Comment by GabeIsman** [comment]
So, I was thinking it would be convenient to edit directly in a list when you are doing a task like adding a series of people to an organization, or adding a bunch of recordings. The flow of 
`/recordings/new -> search for org to add it to -> save -> repeat` is not as nice as `search for org page -> hit plus button under recordings as many times as you want -> save them`. If we can come up with a clean flow for `search for org page -> hit add recording button (takes you to /recordings/new) -> save -> redirected (client-side) back to org page` that would probably be best.

**Comment by GabeIsman** [comment]
Sorry, just realized what you were saying about everything coming externally (haven't had my coffee yet this morning). I guess I hadn't even considered that we wouldn't give people a way to edit recordings or people. It seems important to make it possible to edit recordings so that any errors made by our scraper can be fixed, or to link an org that wasn't auto-linked, or to add a title, etc. But that could be done on the single recording page? Is there a single recording page?

I've updated the issue title to reflect the new question.

**Comment by melodykramer** [comment]
I defer to @nkkl on this, but agree that we wouldn't want to give everyone the ability to edit these fields.

**Comment by thequbit** [comment]
Per discussion on hangouts, I think we should just link to the resource that will be edited.  No need to make the tile itself editable.  Closing.
