### ISSUE TITLE
Stub out Organizations page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#115]
This is the big list of organizations with search.  Design and features discussed in #80.

**Comment by thequbit** [comment]
The template for new pages can be found here: https://github.com/mediapublic/mediapublic/tree/develop/client/app/_template

**Comment by GabeIsman** [comment]
This one has been stubbed in https://github.com/mediapublic/mediapublic/pull/113.

**Comment by GabeIsman** [comment]
This is stubbed. Needs to be fleshed out of course, but that's a separate issue.
