### ISSUE TITLE
Stub out User settings page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#119]
Profile, settings, and such. Design and features discussed in #103.

**Comment by thequbit** [comment]
The template for new pages can be found here: https://github.com/mediapublic/mediapublic/tree/develop/client/app/_template

**Comment by GabeIsman** [comment]
Are users and people the same thing? Are people just users with an organization? The semantics seem kind of weird here, maybe we should settle on one name.

**Comment by nkkl** [comment]
Well, it's a little weird because people and users could be a venn diagram. For example, if someone works at a station we probably want to have their info even if they aren't registered with our site. And conversely, just because someone has an account with us doesn't mean they're formally affiliated with a station.

**Comment by thequbit** [comment]
I think we should have a field in the `Users` table that is `organization_id` and let it be nullable.  If it is NULL, the user is not apart of an `Organization`.  If it is not NULL, then they are a `Organization` employee.  I think it should be displayed on the client as "People", but really we'll be querying for "Users".

**Comment by GabeIsman** [comment]
So this page will actually be a "People" page, right?

**Comment by thequbit** [comment]
The issue name misleading, should have been User not Users. This page is the user's settings page of sorts. Does that make sense?

**Comment by GabeIsman** [comment]
Got it, the issue description was also misleading, ha. Edited for clarity.

**Comment by thequbit** [comment]
My bad.   Thanks for cleaning it up!

**Comment by thequbit** [comment]
Yea, definitely copy-pasta'ed that from the others.  Sorry about that @GabeIsman.

**Comment by GabeIsman** [comment]
Note: I think this will end up being the same page that admins use to manage the people associated with their organization, so it could potentially also include an add/remove organization feature.

**Comment by thequbit** [comment]
@GabeIsman that makes sense to me.
