### ISSUE TITLE
MVP Scope

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#12]
_Note: this is the contents of a number of comments from another repo.  User's names have been place above the comments to keep a history of what was said._

---

**@thequbit**

We should talk about this based on @melodykramer deleted comment :p.

I'm down to thin things down a bit for the MVP.  And I think the above list is good.

I think we would want to define a set of things that the stations could add/edit ( address, contact info, how to become a member, phone, blurb about them, etc. ).  Then give them the ability to add people to their stations.  This would, again, be a fixed set of fields they could update ( name, mailing address, phone, twitter, focus, etc.).

Stations would also be able to create a list of audio recordings ( linked back to their site, we would not host anything ), that they would put into a category.

Finally we could give users the ability to login ( using twitter/facebook/google? ) and create their own play lists that anyone can see/use  ( they would be returned in searches based on listening category ).

The last bit would be Midas integration, which I'll just leave as that ... since we still have lots of questions about that.

This would give us the check boxes for:
- Landing page for each station
- A searchable index of all public media personal
- Crowd-sourced content ( play lists of sorts ).
- "Help me" section

I think it's important to understand where we want to go, though, so we don't have to re-do large sections of code after we get to our MVP point.

---

**@melodykramer**

This seems reasonable to me.

It would be nice if we could make a bookmarklet that would make it really easy for stations to create lists of audio recordings, when they're on the page for the audio recording. 

The station stuff is mainly in that Google Sheet. I think the things they would need to update themselves are:
1. Ways to help us
2. People
3. Podcasts

and associated fields.

The idea of crowdsourced playlists from people would also be really great.

Midas - yes.

And I think all of your checkboxes make sense. 

I want to make sure we're all on the same page before you code, I drum up more funding, and we figure out how to wow Our Currently Secret Funder.

---

**@thequbit**

Definitely want to make sure we're all on the same page before we dive in - hence all the "Question" labels ha.
- Midas fills the requirement of "ways to help us"
- People
- Audio ( podcasts, really anything ... )
- Bookmarklet/Firefox add-on/Chrome extension ( bookmarket being the simplest )
  - So would this be a "I'm on the page I want to put on the site, just click the pull down and click 'add to podcast list' "?

Would the bookmarklet also work with adding people to the site?  I'm all about low low low barrier to entry, and making things super simple.  Just want to make sure I understand the vision :)

---

**@melodykramer**

I think the bookmarklet would be only for audio. I really like the way the one on This.cm works. It adds the link and then says "What makes this interesting?" (111 characters) - we could also have people click on a tag like "listen to before bed" or "listen to during commute" (i.e. limited choices for categorization.)

---

**@thequbit**

Yup, I'm on board with what you're saying.  I would think it would be a pull down of sorts ... really limit the number of categories.

---

**@melodykramer**

Maybe even click a tag 

In the car / Before bed / Pick-me-up / Need a good laugh / Learn something 

---

**@melodykramer**

Just pasting this here over from the gitter.im

As a user, I want to be able to help by tagging content so that it can be resurfaced in different ways.

As a user, I want to be able to see content that is tagged in ways other than topic such as activity I’m doing or time of day I’d like to listen or how I’d like to feel while listening to the story.

As a user, I want to be able to see what podcasts, stories, and shows individual stations make and how I can help them.

---

**@Gabelsman**

This scoping down makes sense to me. Seems like a reasonable feature set.

**Comment by melodykramer** [comment]
@ismcodes I just want to make sure you see this, particularly the past few comments.

**Comment by ismcodes** [comment]
:eyes:
