### ISSUE TITLE
'None' is returned in JSON response when UUID type is absent

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#126]
When a UUID type field is missing from a record (e.g. a user without an organization), the Pyramid json renderer dumps the model as 

```
{
  ...,
  organization_id: 'None',
  ...,
}
```

'None' doesn't mean anything in JavaScript, so this gets parsed as the string 'None' and causes problems (because the server also treats it like the string 'None', which is not a valid UUID).

This is somewhat puzzling to me because `json.dumps(None)` produces the accurate string 'null', which gets parsed correctly. So the Pyramid JSON renderer must be using something other than the core `json` module under the hood. Bad news. 

There is a way to [change renderers in Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/renderers.html#changing-an-existing-renderer), but I don't know enough about the framework to feel confident that that's the right solution.

**Comment by thequbit** [comment]
We "cast" to a string, since UUIDType isn't json serialize-able.

https://github.com/mediapublic/mediapublic/blob/develop/server/mediapublic/models.py#L202

That should read:

```
organization_id=six.text_type(self.organization_id) if self.organization_id != None else None,
```

( or something similar ).

**Comment by GabeIsman** [comment]
Got it, I'll take a crack at fixing this.
