### ISSUE TITLE
Set up a staging server

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#142]
I think it's time we started thinking just the tiniest bit about devops. Don't want to leave it to the very last minute. I propose we stand up a digital ocean droplet (or equivalent) and work up a set of scripts and nginx configs to get this thing serving.

**Comment by GabeIsman** [comment]
I got a brief start on this just now. Going in the direction of nginx on digital ocean.

**Comment by ryansb** [comment]
What OS are we targeting, CentOS?

**Comment by ryansb** [comment]
Oh, just read your script and it looks like ubuntu/debian

**Comment by GabeIsman** [comment]
Yep, it's Ubuntu.
