### ISSUE TITLE
Where should XMLHttpRequests be made?

### ISSUE THREAD

**Issue by ismcodes** [mediapublic/mediapublic#156]
It would be convenient to make HTTP requests from Backbone/Marionette, but that would put more stress on that server- delegating that work to the client's device could reduce the load. Also, if the data from the response is needed to render a view, I would think that the server would need to wait for that request to come back in order to render the template with that data inside, thus increasing the perceived load time.
So the question is, XHR requests in the Marionette server or in the client's browser?

**Comment by GabeIsman** [comment]
I'm not sure I understand your question. Marionette is a client-side framework--a layer on top of Backbone--that we are using to structure the client app. The client makes a lot of XHRs already, and adding one should be no problem. What problem are you trying to solve?

In general, XHRs originate in a model. See any of the models in the client app for an example. The XHR is made when `fetch` or `save` is called on a model. There is already a recording model--whose job it is to communicate with the `/recordings` endpoint--and you will want to make a corresponding podcast model.

**Comment by ismcodes** [comment]
That makes sense. I think I assumed that Marionette ran off a node server, but that seems to be just serving the static files. Thanks for clearing it up.
