### ISSUE TITLE
Investigate integrating the US Web Design Standards

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#158]
It's been suggested a couple of times that we leverage the UI components and design from the [US Web Design Standards](https://playbook.cio.gov/designstandards/). At first glance this seems like it's going to be very challenging to integrate, since we are using a module-based system for dependencies, and the components are not organized as modules. Worth investigating a little more though before we abandon all hope.

**Comment by nkkl** [comment]
It's worth noting that the designs I've been exploring have largely followed the posted standards. There are some areas where the documentation is unclear (especially around their grid system), but the colors and typography are pretty in line with the guidelines.

That said, I haven't found any particular "special sauce" in the standards that an experienced team can't independently devise. I get the feeling that they're most useful to an incomplete or inexpert team.

**Comment by GabeIsman** [comment]
@nkkl Got it, that's good to know. I think I have some stylistic disagreements with the design standards from an aesthetic perspective (although I like the fonts). The colors feel very generic American. Which may or may not be what we're going for. I also don't really like their inputs (particularly the focus states). Probably a bit of not-invented-here syndrome going on :), but my personal preference would be to not hew too closely to these standards.

**Comment by nkkl** [comment]
Agreed. We can have a quick chat about colors and personality, and I'll work within that to find accessible color combinations. I've worked with the [OLPC](http://one.laptop.org/) accessibility guidelines, and done plenty of checking for accessible color combinations outside of that.

I'm less experienced with screenreaders, but we should be able to look up a good checklist for that as well.

**Comment by GabeIsman** [comment]
Yep. We will need to do a screenreader audit at some point. I've been sprinkling `aria-label`s and `aria-role`s, etc whenever I remember, but I'm sure I've missed some. Also I've been paying no attention at all to to `tabindex`es and screenreader navigation, which a framework wouldn't really help anyway. I'll open an issue so we don't forget.

**Comment by nkkl** [comment]
A++

**Comment by GabeIsman** [comment]
Spent a few more minutes looking into this, and I think this is not going to be worth the headache.
