### ISSUE TITLE
Design search results page.

### ISSUE THREAD

**Issue by nkkl** [mediapublic/mediapublic#161]
- [x] Recordings / Podcasts (Media)
- [x] How Tos
- [x] People
- [x] Organizations

**Comment by GabeIsman** [comment]
Current page above the fold:
<img width="1429" alt="screenshot 2016-01-05 10 48 38" src="https://cloud.githubusercontent.com/assets/697801/12124258/f97bb05a-b399-11e5-967e-2cdca12ad088.png">

below the fold:
<img width="1417" alt="screenshot 2016-01-05 10 48 46" src="https://cloud.githubusercontent.com/assets/697801/12124383/13e306c8-b39a-11e5-9f19-dda1077b186b.png">

**Comment by nkkl** [comment]
Resolved with #190
