### ISSUE TITLE
Figure out isAdmin distinction on the client

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#164]
We need a signal for isAdmin vs. not and need to show/hide the relevant edit buttons. Basically client permissions need to be sorted out.

**Comment by GabeIsman** [comment]
@thequbit How does the backend store/manage admin permissions? How do I determine if a user is an admin?

**Comment by thequbit** [comment]
I can supply a "is_admin" boolean in the user response.

I think I would lean to creating a class ...

```
.isAdmin {
    display: none;
}
```

And then on each page load, after rendering is complete, if user.is_admin is true, then find all elements with isAdmin and do .show().

Right now we do it with UserTypes, but for this MVP I can just make it a boolean in the user table itself.  And then only give access to set that flag from users that are already admin ( so in the beginning only a system user would be able to give permissions ).  Does that make sense?

**Comment by GabeIsman** [comment]
That sounds good to me!

Do we have a general solution for pulling in related models (such as UserTypes in Users)? There are a bunch of cases where related data would be useful to include by default.

**Comment by thequbit** [comment]
Yea, I'm working on the related data thing.  That's where that Zope stuff burned us.  I'll work on figuring that out this evening.

**Comment by thequbit** [comment]
so I am adding `is_site_admin` and `is_org_admin`.  That way we can have site-wide admin things, and just organization admin things.  @GabeIsman does that make sense to you?  We can just trigger everything off of `is_site_admin` for now, I think.

**Comment by GabeIsman** [comment]
Fixed by #180.
