### ISSUE TITLE
Add example wiki page for REST end-point

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#20]
Since we're still _kind of_ in limbo about REST end point definitions, I'll add an example of a wiki page for one of the existing ones.  We can modify/delete/etc. as needed in the future.

@GabeIsman would be looking for your "sign-off" on the format before closing this.

**Comment by thequbit** [comment]
Not yet done :(.  Will get to this tomorrow.

**Comment by thequbit** [comment]
Created an index page:

https://github.com/mediapublic/mediapublic/wiki/REST-End-Point-Index

And an example REST page for /organizations ( will fill in momentarily ):

https://github.com/mediapublic/mediapublic/wiki/REST-End-Point----organizations

**Comment by ryansb** [comment]
So if the idea is "document REST endpoints for humans to read" a format like swagger would be preferable to a wiki page. 

It has a swanky [editor](http://editor.swagger.io/#/) and can generate nice docs for developers. Some languages can also autogenerate clients from swagger docs, which is pretty great.

**Comment by thequbit** [comment]
Removing from milestone.  Will need to investigate the best way to document endpoints.

**Comment by thequbit** [comment]
Closing this.  I will re-open as a new ticket when we have a better idea of our direction for system-wide documentation.

**Comment by ryansb** [comment]
Fun fact: cornice can autogenerate sphinx docs, so I think it'd make a lot of sense to standardize on sphinx for API, deployment, developer, and usage docs.

**Comment by thequbit** [comment]
Agreed.  I'll pick your brain about that at some point in the next "sprint".
