### ISSUE TITLE
Have MVP definition meeting

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#23]
This is assigned to everyone.

As @nkkl suggested [here](https://github.com/mediapublic/mediapublic/issues/17#issuecomment-123879667), we really should have an meeting about our actual MVP definition.  We've had some great async communication up to this point, but I agree with @nkkl we should get everyone in the same _virtual_ room.

I'll send a follow-up email to this issue with a proposed agenda and some dates.

**Comment by melodykramer** [comment]
I propose Tuesday or Wednesday evening, any time after 5pm ET. @nkkl @thequbit @GabeIsman

**Comment by thequbit** [comment]
I can usually do any day after 7:30pm Eastern, but could make something happen at 7 if need be.

**Comment by GabeIsman** [comment]
Both Tuesday and Wednesday are fine with me!

**Comment by thequbit** [comment]
I think we can close this one, since we had our meeting.  We can keep async chat available [here](https://github.com/mediapublic/mediapublic/issues/24)
