### ISSUE TITLE
Sketch out the first Newsletter

### ISSUE THREAD

**Issue by melodykramer** [mediapublic/mediapublic#25]
Who We Are:

SHOW AND TELL

Sketch: Vision Statement and maybe page flow

Questions: Are people excited by this vision statement? Are there any points that are confusing? Are there any thoughts that don't apply to them?

**Comment by melodykramer** [comment]
@nkkl

**Comment by nkkl** [comment]
Please have thoughts.

[image: Inline image 1]

**Comment by thequbit** [comment]
@nkkl you're image didn't come through ... can you upload to imgur and post link here?

**Comment by nkkl** [comment]
![image](https://cloud.githubusercontent.com/assets/766654/8999525/7975397e-36f0-11e5-97aa-37a4d8dac685.png)

**Comment by thequbit** [comment]
This is amazing.  Way awesome.

**Comment by melodykramer** [comment]
OH YES.
