### ISSUE TITLE
Admin Functions

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#3]
_Note: this is the contents of a number of comments from another repo.  User's names have been place above the comments to keep a history of what was said._

---

**@thequbit**

So I had the thought that maybe the Admin functionality of the site should actually be built into each page.  So that when someone is viewing the page as an Admin, they have little (+) next to things, where they can just add a new item.  I've done this before on a few sites with high success in usability, although the target audience was more technical then I think our Admin's may be ...

The thought would be that if you wanted to add something to the site ( and really everything on the site is a list: people, recordings, stations, etc. ) you would just click a "add" button.  And that would then just create a new field right there on the site.

I know this won't work with all things ... but it could be adapted pretty universally I think ( or modals could be used to supplement as needed ).  As @GabeIsman said, this site is kinda big, and we haven't even touched on the "how do we get data into it" part yet.  We can pre-fill things all day from scripts, but eventually we'll need to push that "burden" onto the stations and users.

---

*_@melodykramer *_

I think this is a good idea!

---

**@Gabelsman**

I like this idea. I think we'll need to be careful designing it so that it doesn't turn into an unholy mess on the code side, but I think it's a usability win. If we do it right, the code ought to be fairly general too.

---

**@thequbit**

I think we can spend some time to, like you said Gabe, 'do it right' and make it pretty clean.  Any time there is a list, we can just define the items that go into that list and then make those things into inputs.  Something like:

```
var list_item = [
    {
        name: 'name',
        type: 'input/text',
    },
    {
        name: 'age',
        type: 'input/digit',
    },
    {
        name: 'hair_color',
        type: 'combo',
        combo_contents: [
            {
                text: 'Brown',
                value: 0,
            },
            {
                text: 'Blond',
                value: 1,
            },
            {
                text: 'Red',
                value: 2,
            },
            {
                text: 'White',
                value: 3,
            },
        ]
    }
```

This way we can just have the code render the fields, and validate them before submit ( that will be done server side as well, but much easier to check them client side first ).

I agree that usability should be one of ( if not our highest ) priority.

---

**@Gabelsman**

Makes sense to me. I've had some success working with https://github.com/powmedia/backbone-forms (on backbone projects), I'm sure there are tools in other frameworks for turning a JSON representation of a data structure into a working form with validation, etc.

**Comment by nkkl** [comment]
Agreed. Shouldn't be hard to do some UI design that makes it very clear when you're in admin mode and what you can edit to make it friendlier to our least tech-enthusiastic users. Ideally this can be fairly WYSIWYG.

**Comment by GabeIsman** [comment]
We have adopted this approach wholeheartedly!
