### ISSUE TITLE
HTTP status codes used improperly

### ISSUE THREAD

**Issue by ryansb** [mediapublic/mediapublic#30]
Any caller to `check_payload` that sends invalid JSON gets an error back, but returns an HTTP 200.

For example, when sending a malformed user, I get:

```
200 OK
{"error": "Invalid JSON"}
```

**Comment by ryansb** [comment]
I'll have a patch up for this soon.

**Comment by thequbit** [comment]
:+1:

I was just thinking this yesterday,  and forgot to open a ticket.   Thanks!

**Comment by thequbit** [comment]
Closed by #32 .  Thanks @ryansb !

**Comment by ryansb** [comment]
\o/
