### ISSUE TITLE
Update tests with new endpoints

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#38]
Need to update tox tests with all new endpoints.

**Comment by ryansb** [comment]
Do you feel confident enough with Gabbi to do all of them?

**Comment by thequbit** [comment]
Nope, not at all.  But I'm confident that I'll be able to get it somewhat done enough to submit a PR and have you tell me what I did wrong :package:

**Comment by GabeIsman** [comment]
@thequbit this is done now right?

**Comment by ryansb** [comment]
Yeah, he added those tests.
