### ISSUE TITLE
Implement REST endpoints within backbone.js

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#39]
We need to define all of the REST endpoints within backbone.js so they can be used within the front-end client.

@GabeIsman assigning this to you, but don't feel pressured to get all of them implemented.  If you just do one, I'm sure I can copy pasta all the things.

**Comment by GabeIsman** [comment]
Closing this as obsolete. The rest integrations will be accomplished as the relevant models are built out.
