### ISSUE TITLE
Set Access-Control-Allow-Origin header on API responses

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#40]
This is not the only solution of course. We could put a server in front of the api and webserver, and may want to do that eventually, but for now a permissive access control policy will enable developing against the api.

**Comment by GabeIsman** [comment]
http://stackoverflow.com/questions/21107057/pyramid-cors-for-ajax-requests

**Comment by ryansb** [comment]
I see, CORS support is builtin for cornice. Also, we should talk about the design of the endpoints. It's possible to use UWSGI to serve the static content in addition to the REST server. 

Example:
/ would go to the JS application
All API enpoints would live at "/api/v1/<ENDPOINT>" and that path would be munged by UWSGI.

**Comment by ryansb** [comment]
Obsoleted by #44
