### ISSUE TITLE
Add Twitter Oauth capability to backend

### ISSUE THREAD

**Issue by ryansb** [mediapublic/mediapublic#49]

**Comment by thequbit** [comment]
We'll want a solid way to turn this off for development.  We talked about this in our meeting the other day, and I think it will be important.

**Comment by ryansb** [comment]
Yeah, my thought was to have a way to short-circuit it in development to statically set a user to be used as the authenticated identity (e.g. a twitter username)

**Comment by ryansb** [comment]
Just an update for everyone - I've been working on this over the weekend and haven't gotten all that far. I have [velruse](http://pythonhosted.org/velruse/) integrated, but not the data models needed to retain user secrets.

**Comment by thequbit** [comment]
Ryan, what can I do to help?  Have you touched the models at all?  I think I can do it he JSON extras real quick here, if that would help.

**Comment by ryansb** [comment]
I just need to keep working on it. OAuth is just a pain to get running when you don't have a public IP. 

I've edited the user model a little. You can go ahead and do the JSON extras stuff, but it's not going to be helpful for OAuth stuff.

**Comment by thequbit** [comment]
Kk, I'll do my best to submit the PR this afternoon.

**Comment by ryansb** [comment]
See #51

**Comment by ryansb** [comment]
Actually, I'm going to close this and move discussion to the PR.
