### ISSUE TITLE
Add `extras` field in model objects

### ISSUE THREAD

**Issue by ryansb** [mediapublic/mediapublic#50]
To help make it easier for frontend devs to make changes, add an "extras" field that can contain arbitrary JSON and will be stored by the server. 

Anything in the extras field that seems like it will stay can be moved to an actual field, of course.

**Comment by thequbit** [comment]
I'll take this on this one, and try and get a PR in the next few days for your review @ryansb .

**Comment by thequbit** [comment]
Clearly my last comment was a lie.

@ryansb do you have a good resource to start with for this, so I don't end up too far down the wrong path?

**Comment by ryansb** [comment]
Here's the [postgres docs](http://www.postgresql.org/docs/9.4/static/datatype-json.html) for JSON, and here's a [gist](https://gist.github.com/ryansb/3ad9b7ccf225d46a16dc) I made using it with SQLAlchemy. The main difference between the IPython notebook is that you'll be using the ORM. I'd recommend using a mixin to add the field to the models.

**Comment by ryansb** [comment]
There's also [this article](https://www.compose.io/articles/using-json-extensions-in-postgresql-from-python-2/) which includes using the ORM.

**Comment by ryansb** [comment]
@thequbit do you mind if I take this ticket?

**Comment by thequbit** [comment]
Go for it @ryanasb -  my bad for letting it slip to many times. Let me know how I can support ya.

**Comment by ryansb** [comment]
@thequbit review #50 please :)

**Comment by GabeIsman** [comment]
This was completed by @ryansb in #88!
