### ISSUE TITLE
MVP REST end points

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#6]
_Note: this is the contents of a number of comments from another repo.  User's names have been place above the comments to keep a history of what was said._

---

**@thequbit**

Here is my suggestion for what REST endpoints there should be for our MVP:

_A note on users: I think we really want to do OAuth2 against twitter/facebook/google for logins.  I've only done this for OAuth and it was a few years ago but I'm sure I can figure it out :p. With that being said, there may not be much  that these end points would include, but I figure we should stub them out regardless._

```
# users
[     POST,            ] /users
[GET,       PUT, DELETE] /users/:id

# organizations
[GET, POST             ] /organizations
[GET,       PUT, DELETE] /organizations/:id
[GET, POST,            ] /organizations/:id/comments
[GET,       PUT, DELETE] /organizations/:id/comments/:id

# people
[GET,                  ] /people
[GET, POST,            ] /organizations/:id/people
[GET,       PUT, DELETE] /organizations/:id/people/:id

# recordings
[GET,                  ] /recordings
[GET, POST,            ] /organizations/:id/recordings
[GET,       PUT, DELETE] /organizations/:id/recordings/:id
[GET, POST,            ] /organizations/:id/recordings/:id/comments
[GET,       PUT, DELETE] /organizations/:id/recordings/:id/comments/:id

# learn ( how-to's )
[GET, POST,            ] /howtos
[GET,       PUT, DELETE] /howtos/:id
[GET, POST,            ] /howtos/:id/comments
[GET,       PUT, DELETE] /howtos/:id/comments/:id

# blog
[GET, POST,            ] /blog
[GET,       PUT, DELETE] /blog/:id
```

As for HTML response pages, I figure the following makes sense:
- / (index)
  - Single site blob

And for 'virtual' hash pages ( just the top level ones ... a few more for each 'view' page ):
- /#/home
  - this would be the "google style entry via search" page.
  - a map of the US ( and canada? ) with the stations marked out
  - all stations listed by state
  - search would make the stations disappear/appear as the search criteria changes ( like http://fortawesome.github.io/Font-Awesome/icons/ )
- /#/listen
  - this would be a search with a pre-defined search criteria of audio ( same search style as /#/home )
- /#/people
  - this would be a search with a pre-defined search criteria of people ( same search style as /#/home )
  - Not sure how we should display people ... geographic region, or by category , or type ... up for debate .
- /#/howtos
  - this would be a search with a pre-defined search criteria of how-to's ( same search style as /#/home )
  - "pinned" how-to's
  - top 5 how-to's in each category maybe?
- /#/blog
  - this is a normal blog page.  maybe displaying the first n words of each post of sorts.

@GabeIsman and @melodykramer can you review and add any additional things you think are appropriate?  As you add comments, I'll update the ticket contents to reflect those changes.  Once we get these pinned down, I'll make a Wiki page for each end point, and stub out the Wiki pages for each of the "virtual hash" pages.

---

**@Gabelsman**

+1 for not rolling our own comments. That's a headache we don't need.

**Comment by GabeIsman** [comment]
These are pretty much all implemented now.
