### ISSUE TITLE
Implement routes for /people, /recordings, /howtos

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#64]
These are subresources of the organization resource (I think). There is no established pattern for dealing with subresources in the API implementation so far, so this will take some thinking.

**Comment by ryansb** [comment]
I'm not sure I agree. The problem I see with subresources is that not every query for these things will have an organization associated. For example querying for the popular howtos or getting  the user with a certain Twitter handle. 

I haven't implemented a full filtering API, but I think for these endpoints the way to go would be `/people?org_id=123456`.

**Comment by GabeIsman** [comment]
That's fine with me. However we want to implement it, I think this is pretty high-priority.

**Comment by GabeIsman** [comment]
@thequbit finished this with https://github.com/mediapublic/mediapublic/pull/77.
