### ISSUE TITLE
In-place editing architecture + example

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#65]
We've decided to use the in-place editing paradigm for our all of our admin tasks. This is going to be a substantial effort on the front-end and I want to do some research and architecting/thinking it through. My goal for this is issue is to come up with a repeatable structure/set of abstractions, and implement them for the models on the basic organization page.

**Comment by thequbit** [comment]
@GabeIsman has the beginning of his proposed framework for this [here](https://github.com/mediapublic/mediapublic/commit/2ab877c80acf8dcff05c1a8bfc7dfc1525e160b9).

**Comment by GabeIsman** [comment]
This is done! I'm sure there will be more to iron out as we go, but this is no longer a primary focus.

**Comment by thequbit** [comment]
:+1: yay!
