### ISSUE TITLE
Friendlier API errors

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#68]
Currently when I hit `/organizations/notavaliduuid` I get an `ERR_CONTENT_LENGTH_MISMATCH` from the browser with no content. The app is getting the expected `ValueError: badly formed hexadecimal UUID string`, but that isn't being translated back. This should return 400 with a descriptive error (or at least something).

**Comment by ryansb** [comment]
So in that case we should be returning either a 400 or 404, depending on your philosophy. Since a non-hex UUID _cannot_ be valid, I'd lean toward 400.
![400](https://http.cat/400)

Though it is also not found (as it does not exist) and could count as 404. 
![404](https://http.cat/404)

**Comment by GabeIsman** [comment]
This is fixed.
