### ISSUE TITLE
Division of labor

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#7]
_Note: this is the contents of a number of comments from another repo.  User's names have been place above the comments to keep a history of what was said._

---

**@thequbit**

If we go with option 2 from #2, I think it's appropriate to define who is working on what.

I personally would like to do the back-end server, and use Python2.7/Pyramid/SQLAlchemy to do it.  Can the other members on the team submit what they would like to work on and the technologies they plan on using?  I think this would be good to document for a process on how we divide up things.

---

**@Gabelsman**

I've got a front-end workflow that looks something like:

Backbone - routing, views, event binding, REST integration, etc.
jQuery - dom manipulation
npm - package management
gulp - build automation
browserify - dependency management
sass - css sanity
and others that I am forgetting

This has been working well for me on relatively smaller projects. I could see swapping backbone out for a more heavy-duty framework, although this would come with a lot of learning curve overhead. My preference would be to use React for views, and keep Backbone for the data modeling and routing. I think this approach would still come with a learning curve for me, but I expect it to be much smaller.

---

*_@melodykramer *_

I would like to focus on creating content, fundraising, articulating our goals to clients and funders, figuring out how to integrate social/community hooks, and audience engagement (how do we include people who don't code? How is our documentation?) 

---

**@thequbit**

> Backbone - routing, views, event binding, REST integration, etc.

I've not worked with Backbone before, but it looks simple enough to pickup.

> gulp - build automation

I've used grunt.  My understanding is that they are very similar.  Whatever you feel more comfortable with, you should use.

> I could see swapping backbone out for a more heavy-duty framework, although this would come with a lot of learning curve overhead.

I'm all about learning new skills/software, but in this case I don't think taking on that risk is worth it.  I say we stick with what you know.

> My preference would be to use React for views, and keep Backbone for the data modeling and routing. I think this approach would still come with a learning curve for me, but I expect it to be much smaller.

What ever you think is an appropriate level of risk to ensure that we can deliver on time, and that the code base doesn't be come a spaghetti storm.

I'd put my javascript at a 7/10 or so.  I'm not super 1337 JS coder, but I can certainly contribute constructively :).  I do not believe the back-end will take me very long at all, so I don't mind diving into the front-end stuff.  I think we'll just need to take the time to understand each others coding styles, and make sure we're not stepping on each others toes ( too much ).

So with that all being said, if we are going with our "option 2" architecture, I think it might be wise to split the front-end and back-end up into two different repo's.  Especially since they are in two different languages.  The mediapublic-server and the mediapublic-frontend ( or -website, or -site, or ... ).  This keeps the division clean.  The one thing that will be important to is to make sure we are keeping track of versions so they match up well ( year.major.minor seems to work well for me.  major versions work together and minor versions just are bug fixes and features and whathaveyou ).

Does that make sense to you @GabeIsman ?

---

**@thequbit**

@melodykramer I'm so pumped that you want to do that, and ( from what I can tell ) are very good at it.  I think that is where some of my other projects have failed ... that we didn't have someone dedicated to those things, but it was the coders job to try and find time to do it.  

Does it make sense to pull the trigger on all the social things now?  Twitter/Facebook/G+/Instagram/Github/Website URL/etc. ?  I think we may already have some of those? yes?

---

**@melodykramer**

Yes, I think all projects need to think about that from Day 1. I also plan to write down and articulate why we're building each feature (and what user question is answers) which I think will be useful for us, but also funders. Will start to scoop up all of the social / web handles today.  @thequbit 

---

**@thequbit**

Yea, I like that a lot for the funding conversation. "These are the problems we've identified, and these are how we are ( or are planning on ) solving them."  Nice and clear to see. :+1:

---

**@Gabelsman**

@melodykramer It's so exciting to be working on an open source project with people who want to work on non-coding aspects!

@thequbit I want to push back a little on the two repos idea. I would prefer to have everything in one repo with top level folders for 'server', 'client', etc. I think that this approach has some major benefits:
- No need for complex or strict versioning. If I want to add a small front-end feature that requires a small change, that's one PR instead of PR, version bump, PR, version bump. Note that this doesn't preclude versioning around breaking changes, etc. Just makes it not a requirement.
- Lower cognitive overhead/easier onboarding. Nobody ever has to ask or be told where to file an issue or which repository to fork.
- Easier automation of deployment and dev environment set up. One repo means the deployment/install scripts can live in the repo and setup/deploy the whole thing in one shot. Git clone && setup.sh is pretty straightforward. 
- We can still have clean separation, just enforced at directory boundaries instead of repo boundaries.

What are your thoughts?

---

**@thequbit**

@GabeIsman I don't disagree with any of the above.  I've just gotten myself into intertwined hell with having server and client in the same repo, that's all.  I'm pro a single repo ( def for the on-boarding and the setup portion ), I think we ( I? ) just nee to be vigilant about keeping things separate.

Let's, for now, go ahead with the single repo.  If we come across a need to break things up, we'll cross that bridge when we get there.

+1 for push back.

---

**@Gabelsman**

@thequbit :+1: 

I think starting from a monolith and moving to more separation as necessary is the right approach.

On that note, should we rename this repository? What is the mediapublic repository for?

---

**@thequbit**

I think Media-Public/mediapublic should be reserved for things like process and documentation.  It is kind of the collection of 'non-technical stuff' ... or at least that's what my thought was?

I would be okay renaming this to mediapublic-website ...

Thoughts?

---

**@Gabelsman**

I have a general bias for fewer repositories. I guess the question should be, should the process/documentation workflow be separate from the code workflow for any reason? Do we want the issues in separate places? I don't know the answer to that, but my inclination would be to say that we should just have one big repo. Thoughts @melodykramer?

---

**@melodykramer**
I'm open to either. I'm thinking about ways to mask the other repo with prose.io or something similar to make it friendly for non-coders. There are people across the public who should weigh in on this project and I don't want GitHub to be the barrier that stops them.

What do you think @GabeIsman? 

---

**@Gabelsman**

I'm not familiar with prose.io and similar. I wonder if there is a way to scope which folders are editable from that interface?

Additionally, something worth considering: presumably we're going to be directing people to contribute by saying something like 'go to this url and find an issue that looks interesting and get started.' Do we want those people to see code issues, or just docuementation/content/ideas issues? IMO, that seems like it should be the deciding factor. I'm fine with either approach.

---

**@thequbit**

I'm down to have a conversation over an appear.in to figure out repo seperation.  We should figure this out quickly so we're not renaming things later down the line ...

My vote is to have a main repo that is a collection of all non-technical things.  Here would live information on how to contribute to the project ( technically and not ).  Then all other things that we create ( presumably code ) would live in their own repo's.  This would include any spin off tools and the website itself.

I'm open to all suggestions though ... would like to get this pinned down sooner than later so we can continue moving forward with all this great momentum!

---

**@melodykramer**

I think that's a good approach @thequbit - We seem to have both mediapublic (project) and media-public 

The GitHub page is mediapublic.github.io

I may have inadvertently screwed this up by registering both a project and a series of repos. I'm happy with either one but want to make it the easiest on us. 

---

**@melodykramer**

We should think about where to put this information / passwords / etc. I will work on filling out these profiles and getting them ready. 

domain - mediapublic.io
Twitter - @themediapublic
Facebook - www.facebook.com/themediapublic
Gmail - themediapublic@gmail.com
Google Analytics - UA-65064906-1
G+  - themediapublic

**Comment by GabeIsman** [comment]
It think this question has been largely resolved.
