### ISSUE TITLE
Decide what information will be on the homepage.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#79]
We need to decide what information will be on the homepage of mediapublic.io.  I think some graphics and a brief description makes sense, but it probably doesn't need to be too busy.  Alternatively, we can make the proposed `/organizations` page the homepage ( see #78 ).

Thoughts?

**Comment by melodykramer** [comment]
I think minimal is best as long as people can search and/or navigate and find everything else. I really like the way [open foia](https://open.foia.gov/) handles this. Everything is through the search bar.

**Comment by thequbit** [comment]
I like that a lot.  Could be the Media Public banner, then "Station List" and "Howtos" on the top.

Then below we can have a "What is MediaPublic"  "What are Howtos" "Read our Blog" kind of blurbs.  I think this is a solid starting point.

With regard to search: we'll have to do some thinking about how search will work.  There is going to be quite a bit of information loaded into the site, and we'll need to prioritize results.  This also introduces another page ( search results ) and more end points.  We may want to hold off on the search bar for the moment, and just have some large icons that you can select that are the different parts of the site. 

Or, and I think I like this more for our MVP, we could have a drop down that selects which search you are performing ( howtos, blog, stations, people ) and then it just forwards to that search result page.  I think that could be done easily.

Thoughts?

**Comment by melodykramer** [comment]
Yes, I think that works really well as an MVP - and I'm happy to do user testing (and send this out to the newsletter) 

I like the idea of a drop down.

**Comment by nkkl** [comment]
Melody, can we in particular start testing copy with our readers? That's going to be at least as big as tuning the layout, and should be faster to do at the right fidelity level.

**Comment by nkkl** [comment]
First crack at a design. Have feelings! :)

![image](https://cloud.githubusercontent.com/assets/766654/11321080/1042dbe4-9066-11e5-89b1-1ae09057822c.png)

**Comment by thequbit** [comment]
Does this seem reasonable for drop-downs on the search?
- Howtos
  - `/howtos?q=<search_term>`
- Stations
  - `/stations?q=<search_term>`
- Podcasts
  - `/podcasts?q=<search_term>`
- Recordings
  - `/recordings?q=<search_term>`
- People
  - `/people?q=<search_term>`
- Blogs
  - `/blogs?q=<search_term>`

Note: there are many reasons why Podcasts and Recordings shouldn't be separate.  We shouldn't focus on solving that problem for the MVP.

**Comment by nkkl** [comment]
How hard is it to present the union of podcasts and recordings? I'm not really familiar with the search functionality we're using.

**Comment by thequbit** [comment]
Not too hard, it would more be "how do you display it".  How would you apply the weights and such if it was just two raw sets.  I don't know enough about Postgres full-text search to know how a union would work with weights.  I'll look into it.

**Comment by nkkl** [comment]
Fair enough. I'll do some thinking under the assumption that we can get the two sets of data if we want, but cannot integrate them in a sensical way. So the question then would become "can we display the results for both in parallel in a way that makes sense to users?"

**Comment by thequbit** [comment]
Could be two different sections I suppose.  That it's really the results for both.  I don't know if there is a good way to do that on mobile though without people never seeing the second set.

**Comment by thequbit** [comment]
From @nkkl 

> A search box is initially, you can search for what you want.  But it's a good idea to give people an idea of what they might want want

Suggestions:
- Keep things curated to start, and then move to automation.
  - The "Discover" area would be curated for the time being.
- Elevator pitch is "you can do this site to do A, B, and C"
  - This will get people started.

@nkkl to provide some more notes later for clarification?

**Comment by nkkl** [comment]
First "sketch" in HTML/CSS up: https://github.com/nkkl/mediapublic/commit/fe097e6a99fcb81074a32da11cb2f04fe06a1ced

![image](https://cloud.githubusercontent.com/assets/766654/11491011/a77fd97a-9792-11e5-8b10-9e684e69d348.png)

In general, it has fonts and colors, but it needs visual tuning. Would love feedback on it. Also @melodykramer if you can get me some placeholder copy to work with, that would be doubleplusgood.

**Comment by melodykramer** [comment]
Placeholder copy is in, on the branch copy-changes

**Comment by nkkl** [comment]
I think we've addressed the spirit of this issue, so I'm going to close it. I have an issue filed on me to modify the tile colors, but overall I think we've locked on our first rev of what info will go on this page. Let's have future modifications be driven by new issues.
