### ISSUE TITLE
User Authorization Levels

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#8]
_Note: this is the contents of a number of comments from another repo.  User's names have been place above the comments to keep a history of what was said._

---

**@thequbit**

So I like to define these up-front so we don't get into a long drawn out conversation of who can do what on the site.  I think there should be four authentication levels, and all end-points need to fit one level.

```
VIEWER
STANDARD_USER
ELEVATED_USER
ADMINISTRATOR
```

**VIEWER**
This is someone who goes to the site and has not logged in.

**STANDARD_USER**
This is someone who has created a login.  They should be able to:
- Change their user profile stuff ( display name, location, etc. )
- Label audio to a category
- Post comments to /organizations /learn and /recordings sections
- Integrate with Midas for posting responses to help requests.

**ELEVATED_USER**
This is someone who works at an organization.  They should be able to:
- Do everything that a STANDARD_USER can do
- Edit their organizations "landing page"
- Add people and recordings to their organization
- Post to Midas for help
- Post to /learn
- Post to /blog??? ( we can talk about this ... i picture "invited blogger from xyz station" kind of thing)

**ADMINISTRATOR**
This is the highest authorized user.  They should be able to:
- Do everything that an ELEVATED_USER can do
- POST/PUT/DELETE anything and everything on the site
- Create new users of any auth level.

Does that make sense?  Have I forgotten anything and/or simplified it too much?  I think we can fit most things into this model ...

---

**@melodykramer**

Yes, and I agree that we should only have certain users posting to the blog. This seems like a good demarcation. 

---

**@Gabelsman**

LGTM

**Comment by ryansb** [comment]
Instead of writing your own authorization system, I'd highly recommend using [pyramid.authorization](https://pyramid.readthedocs.org/en/latest/tutorials/wiki/authorization.html) since it handles the hard parts like actually checking ACLs and mapping them to pieces of data.

**Comment by thequbit** [comment]
@ryansb do you have an example of a ( preferable simple ) project that implements this?  I personally find the Pyramid docs rather difficult to understand.

Also, I really appreciate you comments thus far.  Thanks!

**Comment by ryansb** [comment]
So the last time I used it it was still under zope, but I can probably put together a demo in the next week or so.

**Comment by thequbit** [comment]
That would be maximally awesome.  You da man!

**Comment by GabeIsman** [comment]
Pyramid ACLs have been implemented by @ryansb.
