### ISSUE TITLE
Design the Organization List page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#80]
Per #78, the `/organizations` page will need to have a list of all organizations, grouped by state.  What other information should be on this site?  My thoughts:
- Search bar
  - Dynamic search results similar to the one that is implemented [here](https://fortawesome.github.io/Font-Awesome/icons/)
- City the organization ( station ) is in

I don't think we need anything more than that, and if much more than that is suggested, I think it should be considered out of scope for this MVP.

**Comment by melodykramer** [comment]
Agreed. City is key, though - so people can sign up for cities when they might not realize call letters.

**Comment by thequbit** [comment]
@melodykramer definitely.  I think grouping my State, and then having the City they are in is a good starting point.

**Comment by GabeIsman** [comment]
Are you imagining a list by state, or some kind of map?

**Comment by melodykramer** [comment]
Could it suggest a station based on geolocation (not for MVP.)

**Comment by thequbit** [comment]
@gabeisman I was picturing almost exact what Craigslist has, with points on the lat/lng of the stations on the map. 

@melodykramer yup, I think we can do closest neighbor(s) geo lookup. Postgres has a whole suite of great geo functions available.

**Comment by nkkl** [comment]
Emphasis on displaying stations found as [city - CALLSIGN] for easy identification.

![image](https://cloud.githubusercontent.com/assets/766654/11321296/328bf562-906d-11e5-99c1-1a1f08523654.png)

**Comment by thequbit** [comment]
**Search**
- Do we need filters here?
- I assumed that people would be searching for call signs: "WXXI" or a city: "Rochester".  Where if they searched for Rochester, I would expect WXXI ( Rochester, NY ) and KZSE ( Rochester Minnesota ) to both show up ( and probably others, because there are like 16 Rochesters in the US ).
- I think it would be better if we just had search, with no filter.  If you are looking for a certain person, or a howto, do that in the other search, not this one.

**Display**
- Can we do three across rather than them all down?
  - This might be too nitty gritty for this level of decision right now - if so, ignore

**Comment by nkkl** [comment]
I'm cool with no filters. That seems pretty sensible.

How exactly they're displayed will pivot depending on what information we want to should about them, but generally, yes, a straight up one-column list is not going to be a good experience. :)

**Comment by nkkl** [comment]
Covered by #155
