### ISSUE TITLE
Design the Organization page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#81]
This will be one of the hearts of the site ( and really, it's possible that it will be the most highly trafficked ).  This is the landing page for an organization ( station ).  Per #78, the page will have:
- Station info
  - Address, phone, fax, website, etc.
- List of People
- List of Podcasts
  - List of Recordings for that Podcast

I think it's wise to discuss how the layout of this page will look, and perhaps more importantly the organization of information.  I proposed originally, that there would be collapsible lists for people and podcasts.  I think this is still a valid for moving forward, but we may want to dynamically load some of the information after the list is expanded, rather than have a long load time.

Anyone have any additional thoughts on what information should be on this page?  I believe @melodykramer had some thoughts on including a blurb about how to get involved/become a member.  I think the "become a member" link is important, but the "how to get involved" may end up dropping off our goals list till post-MVP.

**Comment by nkkl** [comment]
First pass at sketching this out under [Design>Organization page](https://onedrive.live.com/redir?page=view&resid=4D8563D93722E38!4431&authkey=!AP0r6ahKern5aYU). Please have opinions!

@melodykramer particularly want your thoughts on the information architecture and user goals. I'm not at all confident about the priority of the different chunks of info - what will be most important to a visitor from another station?

**Comment by melodykramer** [comment]
@nkkl I think that looks fabulous, actually. Could we share it with the newsletter? I'm also really keen on the "how to get involved" bucket, even if it's just three items stations could list that people could click on and comment to help. Would that be okay for MVP? I'm concerned if we don't have that, based on how we applied for the grant.

**Comment by nkkl** [comment]
Makes sense to me! If you have time, we can also hop on a video chat and do some sketching this weekend.

**Comment by thequbit** [comment]
Here is the screen shot of @nkkl's mock up:

![](https://raw.githubusercontent.com/mediapublic/mediapublic/develop/docs/media/orgs_page_mockup.png)

We'll need to call out to the following end-points:

`[GET] /organizations/{org_id}`

Information to be displayed for the org:
- Name ( call letters? )
- Full Name ( "WXXI Public Broadcasting Council", rather than just "WXXI" )
- Description
- Address
- Phone
- Fax
- Primary and Secondary websites
- Social Media links

`[GET] /podcasts?organization_id={org_id}`
`[GET] /people?organization_id={ord_id}`
`[GET] /help_requests?organization_id={org_id}`

I suspect that paging will be the best bet here, since there could be a LOT of things in each of the last three GET's.

Question: **_How many would we load with each "show more"?  6 more? 12 more? 24?**_

Like @nkkl suggested, I think displaying 6 "tiles" for each category on desktop and 3 "tiles" on mobile seems reasonable.  Title contents would be something like:
- Podcast
  - Image of podcast ( could be a symbol and/or the head shot of the host )
  - It's name
  - Number of recordings
  - Date of last recording?
- People
  - Image of head shot ( if available, otherwise some generic silhouette  )
  - Name
  - Position/Title?
- Help Request
  - Title
  - First 10 words of description with a "..." at the end?
  - Tags?

Thank you @nkkl for putting this together!  It come out really awesome!  I think @GabeIsman has a great start with displaying the station info.  I think we should take on the title design next.

**Comment by nkkl** [comment]
Took a second pass the information hierarchy. Let me know what you think! Once we settle on the basics, I'd love to go through with actual data for a station and make a grey-box mockup in HTML. From there we can just integrate it into the codebase!

![image](https://cloud.githubusercontent.com/assets/766654/11321024/63771f02-9064-11e5-878b-9f9320572bfb.png)

**Comment by thequbit** [comment]
Great point with having the links to the how-to's right on the organization page.  This is awesomeness!

**Comment by thequbit** [comment]
Seconds, in order:
- Meta data ( info about the station )
- Podcasts/Recordings
  - Q: does having recordings up higher help encourage people to help.
- Requests for help
- Howtos
- People

_Per discussion on November 29th hang-out_

**Comment by GabeIsman** [comment]
Current page (expanded): 
<img width="1433" alt="screenshot 2016-01-05 10 53 19" src="https://cloud.githubusercontent.com/assets/697801/12124472/93ef6bcc-b39a-11e5-8b98-dc37e40198ce.png">

below the fold:
<img width="1424" alt="screenshot 2016-01-05 10 54 14" src="https://cloud.githubusercontent.com/assets/697801/12124505/b1eaa844-b39a-11e5-9fc9-0e84fe4be494.png">

**Comment by nkkl** [comment]
Design submitted in https://github.com/mediapublic/mediapublic/pull/173!
