### ISSUE TITLE
Decide what information will be on the Howtos page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#83]
Hoping we can re-use some code from the `/organizations' page talked about in #80.  Per #78, this page will include:
- A list of all the howto's, probably something like 10 at a time ( paged )
- Search
  - Search results may need a different page?
- Each item listed has:
  - Title
  - Description
    - Votes?
      - Maybe 1 - 5 star system?
    - Number of comments?

For search, we may need a different page to display the results.  Perhaps with a nice filter of sorts.  I would be okay with a simple list that is doing full-text search for the time being.  Making the separate page gives us the freedom to add things quicker later on.

I think the voting could be pretty slick ( the more entry points for participation the better ), however may be too much to take on.  I think we should make it a stretch goal.

Comments have been talked about, and I think that either rolling our own for demo purposes only, or using Disqus or Facebook is the answer.  I would be down for any of those solutions.

**Comment by melodykramer** [comment]
I'm hesitant to use Disqus because it's not open / Facebook for similar reasons....

**Comment by thequbit** [comment]
We can roll our own for quick and dirty, but I would be really hesitant to "go live" with our own solution unless we had some serious thought put into protections.

**Comment by nkkl** [comment]
This is the browse/search results for How-Tos, yes? (In this case, Browse would be a "you didn't enter specific search terms, so we chose a filter for you" view, which we can treat as an edge case of Search in our design)

**Comment by thequbit** [comment]
I took this to be the page that you describe here: https://github.com/mediapublic/mediapublic/issues/79#issuecomment-158691021as "browse" in the bottom right.  It's the "there are a crap load of howtos, here is how we are going to attempt to organize them for you" page.

**Comment by thequbit** [comment]
Oh, but as @melodykramer points out, we DEFINITELY want to have a comments/feedback section for each howto.  I think that discussion should be moved to #84, since this page is just the "browse and search results" page, not the actual howto content.

**Comment by nkkl** [comment]
Yeah, I think it would be reasonable to throw some metadata on them at some point, but let's not worry about exposing that in our MVP. We're here to learn, right?

**Comment by nkkl** [comment]
Let's keep this one simple.

![image](https://cloud.githubusercontent.com/assets/766654/11321309/c4ea6916-906d-11e5-8203-ebc273b7e19f.png)

**Comment by thequbit** [comment]
:+1:

**Comment by thequbit** [comment]
@nkkl 

> How do you get to the howto page?

We'll start with just posting the last 6 howto's that were posted on the page.  In the future we'll probably move to curation.

**Comment by thequbit** [comment]
Do to our level of abstraction for different pages, the collections pages all end up being very similar.  

The pages that are the same are #83 and #85.
