### ISSUE TITLE
Decide what information will be on the Blogs page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#85]
This should be a pretty standard issue blog listing that is ordered by publish date.  Perhaps a listing of years/months and blog titles that is commonly found.  I think search could be nice here, but I don't think it should be a high priority.  If we build the search stuff in a re-usable way, then we can just copy pasta from `/organizations` and `/howtos`.  Reference #78 for the full site-map.

**Comment by GabeIsman** [comment]
+1 for reusable search. Maybe some kind of full-text index like [solr](http://lucene.apache.org/solr/) or [elasticsearch](https://www.elastic.co/products).

**Comment by melodykramer** [comment]
:+1:

**Comment by thequbit** [comment]
We can actually do full-text search with Postgres!

http://www.postgresql.org/docs/8.3/static/textsearch.html

I think I've come to grips with using Postgres is pretty much cheating, ha.  I think we're fine to use Postgres functionality here until we see an issue with performance.  ElasticSearch is amazing, and I've used it on a number of projects.  I think that the full-text search on Postgres will do just fine though.

I think we can just add a `/blogs?q=` that would perform the search rather than a generic get.

Thoughts?

**Comment by nkkl** [comment]
Is there a reason for Blogs and How-tos to have different UI?

Are we writing the blog entries? How are blogs and how-tos differentiated?

**Comment by thequbit** [comment]
I was thinking that yes, they would be almost identical in their UI.  The `Howtos` are for people within Public Media to provide information, feedback, and experience to their peers ( other users ).  The `Blogs` are for MediaPublic people to present information to the user base.

**Comment by nkkl** [comment]
Perfect. We can basically dupe the UI and change the copy for v1.

**Comment by thequbit** [comment]
:+1:

**Comment by thequbit** [comment]
Per #78 discussion [here](https://github.com/mediapublic/mediapublic/issues/78#issuecomment-158839473), I've moved this to "nice to have".

**Comment by thequbit** [comment]
Do to our level of abstraction for different pages, the collections pages all end up being very similar.  

The pages that are the same are #83 and #85.
