### ISSUE TITLE
Design single blog entry page.

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#86]
A single blog entry.  This could be identical to #84, with a different header.  Blogs are written by MediaPublic folks, and is a way for the team to reach out to the community.  Reference #78 for the full site-map.

**Comment by melodykramer** [comment]
:+1: - Sounds good!

**Comment by thequbit** [comment]
Per #78 discussion [here](https://github.com/mediapublic/mediapublic/issues/78#issuecomment-158839473), I've moved this to "nice to have".

**Comment by nkkl** [comment]
Visually identical to #84
