### ISSUE TITLE
Organizations should have social media profiles

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#98]
The DB schema needs to be updated to accommodate and the UI needs to be update to allow viewing/editing.

**Comment by thequbit** [comment]
I say we put these in the `extras` field for right now.  Good test-run for this method of "just keep pushing forward".  Thoughts?

**Comment by GabeIsman** [comment]
SGTM. Is that extras field going to work transparently on the backend? That is to say, should the posted data look like

```
{
  short_name: '...',
  ...,
  twitter: 'blah',
}
```

or like

```
{
  short_name: '...',
  ...,
  extras: {
    twitter: 'blah',
  }
}
```

The former would be easier to implement on the front end.

**Comment by GabeIsman** [comment]
ping @thequbit or @ryansb.

**Comment by ryansb** [comment]
It's like the latter - you have to put whatever the "arbitrary" stuff is in its own object. The reasoning was that if we stored _all_ the extra keys, that'd make it really easy to accidentally typo keys in API requests.

**Comment by GabeIsman** [comment]
Got it. Thanks @ryansb.
